Repository javalent/initiative-tracker, pull requests merged in 2023-04, with the labels that each got.

#121 chore(master): release initiative-tracker 9.6.0
  .release-please-manifest.json
  TESTING.md
  manifest.json
  package-lock.json
  package.json
Labels: autorelease: pending

#133 fix: properly log automatic unconscious status (close #132)
  src/tracker/stores/tracker.ts
Labels: bug

#118 feat: Temporarily change AC on the fly
  README.md
  index.ts
  src/logger/logger.ts
  src/settings/settings.ts
  src/tracker/player/PlayerView.svelte
  src/tracker/stores/tracker.ts
  src/tracker/ui/Updating.svelte
  src/tracker/ui/create/Create.svelte
  src/tracker/ui/create/Creator.svelte
  src/tracker/ui/creatures/Creature.svelte
  src/tracker/ui/creatures/CreatureControls.svelte
  src/tracker/ui/creatures/Table.svelte
  src/utils/creature.ts
Labels: feature
